export enum ACCOUNT_STATUS {
  WORK = 'WORK',
  AVAILABLE = 'AVAILABLE',
  VACANCY = 'VACANCY',
  NO_CONTRACT = 'NO_CONTRACT',
}

export enum VEHICLE_STATUS {
  WORK = "WORK",
  AVAILABLE = "AVAILABLE",
  PANNE = "PANNE",
  GARAGE = "GARAGE",
}

export enum TRAVEL_STATUS {
  CREATED = "CREATED",
  CANCELLED = "CANCELLED",
  DEPARTURE = "DEPARTURE",
  TRAVELING = "TRAVELING",
  UNLOADING = "UNLOADING",
  CLOSED = "CLOSED",
}

export enum FINANCIAL_TYPE {
  INCOME = "INCOME",
  EXPENSE = "EXPENSE",
}

export enum INVOICE_STATUS {
  CREATED = "CREATED",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
}