export enum ACCOUNT_STATUS {
  WORK = 'WORK',
  AVAILABLE = 'AVAILABLE',
  VACANCY = 'VACANCY',
  NO_CONTRACT = 'NO_CONTRACT',
}

export enum VEHICLE_STATUS {
  WORK = "WORK",
  AVAILABLE = "AVAILABLE",
  PANNE = "PANNE",
  GARAGE = "GARAGE",
}

export enum TRAVEL_STATUS {
  CREATED = "CREATED",
  CANCELLED = "CANCELLED",
  GO_DEPARTURE = "GO_DEPARTURE",
  GO_TRAVELLING = "GO_TRAVELLING",
  GO_ARRIVAL = "GO_ARRIVAL",
  BACK_DEPARTURE = "BACK_DEPARTURE",
  BACK_TRAVELLING = "BACK_TRAVELLING",
  BACK_ARRIVAL = "BACK_ARRIVAL",
  CLOSED = "CLOSED",
}
